print ("Enter your name")
input()
print ("Enter your Maths marks")
Maths = input()
print ("Enter your English marks")
English = input()
print ("Enter your Science marks")
Science = input()
print ("Enter your Hindi marks")
Hindi = input()
print ("Enter your Social Science marks")
Social  = input()
print ("Total Percentage")
print ((int(Maths) + int(English) + int(Science) + int(Hindi) + int(Social))/5 )